<x-layout.store title="Sikkim Store's Dashboard">
    <section>
        <div class="w-screen bg-white">
            <div class="flex">
                <x-dashboard-side-bar :store="$store"/>
                <x-dashboard.content :store="$store" name="Products Create">
                    <form action="{{ route('store.admin.products.store', $store) }}" method="post">
                        @csrf
                        <div class="mb-4">
                            <label for="name" class="block text-sm text-gray-700 mb-1">Name:</label>
                            <input type="text" name="name" id="name" placeholder="e.g. Iphone 12 Pro 64GB Black"
                                   class="rounded-md w-full max-w-md border-gray-300 placeholder-gray-300"
                                   value="{{ old('name') ?? $product->name }}">
                            <p class="text-xs mt-1 ml-2 text-gray-500">For best result, keep it short and to the
                                point.</p>
                        </div>
                        <div class="mb-4">
                            <label for="slug" class="block text-sm text-gray-700 mb-1">Slug:</label>
                            <input disabled type="text" name="slug" id="slug" placeholder="Auto generate."
                                   class="text-gray-500 bg-gray-200 rounded-md w-full max-w-md border-gray-300 placeholder-gray-300"
                                   value="{{ old('slug') ?? $product->slug }}">
                            <p class="text-xs mt-1 ml-2 text-gray-500">Slug is autogenerated unique identifier.</p>
                        </div>
                        <div class="mb-4">
                            <label for="price" class="block text-sm text-gray-700 mb-1">Price:</label>
                            <input type="number" name="price" id="price" placeholder="12400"
                                   class="rounded-md w-full max-w-md border-gray-300 placeholder-gray-300"
                            value="{{ old('price') ?? $product->raw_original_price }}">
                        </div>
                        <div class="mb-4">
                            <label for="category" class="block text-sm text-gray-700 mb-1">Category:</label>
                            <select name="category" id="category"
                                    class="rounded-md w-full max-w-md border-gray-300 text-gray-700">
{{--                                <option disabled selected class="text-gray-500">Select Category</option>--}}
                                @foreach ($store->categories as $category)
                                    <option value="{{ $category->id }}" {{ $category == $product->category ? 'selected' : '' }}>
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-4">
                            <label for="description" class="block text-sm text-gray-700 mb-1">Short Description:</label>
                            <textarea name="description" id="description" rows="4"
                                      class="resize-none rounded-md w-full max-w-md border-gray-300 text-gray-700">{{ old('description') ?? $product->description }}</textarea>
                        </div>
                        <div class="mb-4">
                            <label for="long_description" class="block text-sm text-gray-700 mb-1">Long Description:</label>
                            <textarea name="long_description" id="long_description" rows="4"
                                      class="resize-none rounded-md w-full max-w-md border-gray-300 text-gray-700"></textarea>
                            <p class="text-xs ml-2 text-gray-500">Markdown supported.</p>
                        </div>
                        <div class="mb-4">
                            <label for="image" class="block text-sm text-gray-700 mb-1">Featured Image:</label>
                            <input type="file" name="image" id="image">
                        </div>
                        <div class="mb-4">
                            <label for="product-images" class="block text-sm text-gray-700 mb-1">Product Images:</label>
                            <input type="file" name="product_images" id="image" multiple>
                        </div>
                        <div class="mt-12 mb-4">
                            <button type="submit" class="bg-indigo-600 px-6 py-3 text-sm text-white rounded-md">Create
                                Product
                            </button>
                        </div>
                    </form>
                </x-dashboard.content>
            </div>
        </div>
    </section>
</x-layout.store>
